ses.setup]
cmds = [
    "cd suscridash-backend && pip install -r requirements.txt",
]

[phases.install]
cmds = [
    "cd suscridash-backend && pip install gunicorn",
]

[start]
Cmd = "cd suscridash-backend && gunicorn app:app --bind 0.0.0.0:$PORT"
